//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_omr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public int OrderID { get; set; }
        public string Passenger { get; set; }
        public string PassengerDocNum { get; set; }
        public int PassengerSeatNum { get; set; }
        public string Status { get; set; }
    }
}
