//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_omr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        public int Id { get; set; }
        public int DepBusStopID { get; set; }
        public int ArrBusStopID { get; set; }
        public System.DateTime DepDateTime { get; set; }
        public System.DateTime ArrDateTime { get; set; }
        public string TravelTime { get; set; }
        public int VoyageNumber { get; set; }
        public string VoyageName { get; set; }
        public int NumberSeats { get; set; }
        public int TicketCost { get; set; }
    }
}
